name: Terraform Workflow

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  terraform:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Initialize Terraform
        run: terraform init
        
      - name: Plan Terraform
        run: terraform plan
        
      - name: Apply Terraform
        run: terraform apply -auto-approve
